name: Example
version: 1.0.0
main: com.blocktyper.example.ExamplePlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Example description
commands:
  example:
    description: Example command!